[package]
name = "flowmation-application"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
async-trait.workspace = true
chrono.workspace = true
flowmation-domain = { path = "../flowmation-domain" }
flowmation-workflow-host = { path = "../flowmation-workflow-host" }
futures.workspace = true
iana-time-zone.workspace = true
nix.workspace = true
serde.workspace = true
serde_json.workspace = true
serde_yaml.workspace = true
sha2.workspace = true
thiserror.workspace = true
tokio.workspace = true
tokio-util.workspace = true
uuid.workspace = true

[dev-dependencies]
tempfile.workspace = true

[lints]
workspace = true
